apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Collabdocs-Cluster
  region: ap-south-1

nodeGroups:
  - name: CollabDocs-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 5