apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabdocs-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabdocs-fe
  template:
    metadata:
      labels:
        app: collabdocs-fe
    spec:
      containers:
      - name: collabdocs-fe
        image: ved104/collabdocsapp-frontend:latest
        ports:
        - containerPort: 3000
        env:
        
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: collabdocs-secrets
              key: db_url
        - name: PORT
          value: "3000"
        
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "http://a579d8c33b400483f9fa790f937592ca-1002122303.ap-south-1.elb.amazonaws.com:3000/api/proxy"
        - name: NEXT_PUBLIC_WS_URL
          value: "ws://a579d8c33b400483f9fa790f937592ca-1002122303.ap-south-1.elb.amazonaws.com:3001"
        - name: BACKEND_API_URL
          value: "http://collabdocs-be:8080"
        - name: WS_API_URL
          value: "ws://collabdocs-ws:1234"
        - name: CRON_HTTP_URL
          value: "http://collabdocs-be:8080"
        - name: CRON_WS_URL
          value: "ws://collabdocs-ws:1234"
      
      - name: ws-proxy
        image: ved104/ws-proxy:latest
        ports:
        - containerPort: 3001
        env:
        - name: WS_TARGET
          value: "ws://collabdocs-ws:1234"
        - name: PORT
          value: "3001"
--- 

apiVersion: v1
kind: Service
metadata:
  name: collabdocs-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: collabdocs-fe
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  - name: ws
    port: 3001
    targetPort: 3001
